name: cypress test

on:
  push:
    branches:
      - master
 
jobs:
      
  tests:
     runs-on: ubuntu-20.04
     
     steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: npm install 
        run: npm install
      
      - uses: actions/download-artifact@v2
        with: 
          name: dist
          path: dist
      - uses: cypress-io/github-action@v2
        with:  
         browser: chrome
         headless: true
         command: npx cypress run
         start: npm run start-prod
         wait-on: http://localhost:5000
         
              
  