name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e test
        uses: cypress-io/github-action@v2
        with: 
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: 'http://localhost:5000'

  deploy:
    runs-on: ubuntu-20.04
             
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: build
        run: npm run build
           
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stormy-tundra-98703"
          heroku_email: "matias.himanen@helsinki.fi"
    